// skip comment
1 "fisrt message register testing by %s.\n"
	{detail message testing}

2 "empty testing.\n"
	{detail message testing 2}

3 "empty testing again.\n"
	{detail message testing 3}

4 "File name is null.\n"
	{}

5 "Mode is null.\n"
	{}

6 "Open file failed. file name: %s, mode: %s error: %s\n"
	{}

7 "Cannot open general file with compress level. file name: %s, mode: %s, level: %d .\n"
	{}

8 "Compress level: %d is not in [%d, %d].\n"
	{}

9 "Input IOBuffer is null.\n"
	{}

10 "Input IOBuffer's buffer is null.\n"
	{}

11 "Only support mode "r", "rb" and "rx" for zip file.\n"
	{}

12 "Input buffer is null.\n"
	{}

13 "Read total number of compressed blocks failed.\n"
	{}

14 "Read max size of decompressed blocks failed.\n"
	{}

15 "Lz4 compress buffer failed, compressed size is %d.\n"
	{}

16 "Lz4 decompress buffer failed, decompressed size is %d.\n"
	{}

17 "Support only one file in a zip file.\n"
	{}

18 "Malloc buffer failed for compressing zip file.\n"
	{}

19 "Do not support seeking a zip file.\n"
	{}

20 "Do not support flushing a zip file.\n"
	{}

21 "Do not support telling a zip file.\n"
	{}

22 "Read Lz4 magic number failed.\n"
	{}

23 "Malloc Lz4 src buffer failed.\n"
	{}

24 "Malloc Lz4 dst buffer failed.\n"
	{}

25 "Do not support writing a zip file.\n"
	{}

26 "Lz4 decompress failed, error message: %s\n"
	{}

27 "Zip compress failed, return code is: %d\n"
	{}

28 "Lz4 read failed.\n"
	{}

29 "Lz4 read buffer is null.\n"
	{}

30 "Compression failed : %s\n"
	{}

31 "End of frame error : %s\n"
	{}

32 "Can't create LZ4 decompress context : %s\n"
	{}

32 "Can't create LZ4 compress context : %s\n"
	{}

33 "Number of buffers is not equal to number of sizes.\n"
	{}

