// skip comment
1 "fisrt message register testing by %s.\n"
	{detail message testing}

2 "empty testing.\n"
	{detail message testing 2}

3 "empty testing again.\n"
	{detail message testing 3}

4 "File name is null.\n"
	{}

5 "Mode is null.\n"
	{}

6 "Open file failed. file name: %s, mode: %s .\n"
	{}

7 "Cannot open general file with compress level. file name: %s, mode: %s, level: %d .\n"
	{}

8 "Compress level: %d is not in [%d, %d].\n"
	{}

9 "Input IOBuffer is null.\n"
	{}

10 "Input IOBuffer's buffer is null.\n"
	{}

11 "New IOBuffer failed. Buffer size is %d\n"
	{}

12 "Input bufer is null.\n"
	{}

13 "Read total number of compressed blocks failed.\n"
	{}

14 "Read max size of decompressed blocks failed.\n"
	{}

15 "Lz4 compress buffer failed, compressed size is %d.\n"
	{}

16 "Lz4 decompress buffer failed, decompressed size is %d.\n"
	{}

