// skip comment
// db/util starts from 100:
100 "Successfully read design %s.\n"
	{detail message}

101 "Successfully write design %s.\n"
	{detail message}

102 "Failed to open file %s.\n"
	{detail message}

103 "Failed in checksum: %d (ref_value %d).\n"
	{detail message}

104 "Succeeded in checksum.\n"
	{detail message}

105 "Top cell %s with ID#%ld.\n        Tech lib with ID#%ld (type %d).\n        Timing lib with ID#%ld (type %d).\n"
	{detail message}

106 "Failed to init %s.\n"
	{detail message}

107 "Failed to create directory %s.\n"
	{detail message}

108 "Failed to write %s for %s.\n"
	{detail message}

109 "Rename top cell %s to %s.\n"
	{detail message}
