// skip comment
1 "invalid option type %s.\n"
	{detail message testing}

2 "option %s contains no value.\n"
	{detail message testing 2}

3 "no value for option %s .\n"
	{detail message testing 3}

4 " value %s not recognised\n"
	{detail message testing 4}

5 " data %s not support by option %s.\n"
	{detail message testing 5}

6 " command get option fail.\n"
	{detail message testing 6}

7 " command do not assign default option.\n"
	{detail message testing 7}

8 " option %s should start with -.\n"
	{detail message testing 8}

9 " option %s is mandatory for the command.\n"
	{detail message testing 9}

10 " option %s has dependency %s which is not set.\n"
	{detail message testing 10}

11 " option %s value %d out of range (%d ~ %d).\n"
	{detail message testing 11}

12 " option %s must assign enum strings.\n"
	{detail message testing 12}

13 " option %s get incorrect parameter.\n"
	{detail message testing 13}

14 " user logic error.\n"
	{detail message testing 14}

15 " group get option %s fail.\n"
	{detail message testing 15}

16 " group dependency relation fail for option %s and option %s.\n"
	{detail message testing 16}

17 " group exclusive relation fail for option %s and option %s.\n"
	{detail message testing 17}

18 " option %s data type incorrect.\n"
	{detail message testing 18}
