// skip comment
1 "Creating %s %s failed.\n"
	{}

2 "More than one %s %s exists.\n"
	{}

3 "Could not open %s for writing.\n"
	{}

4 "Please specify the %s file.\n"
	{}

5 "The file %s specified does not exist.\n"
	{}

6 "Cannot find %s when %s.\n"
	{}

7 "No value specified for "%s" option.\n"
	{}

8 "%sRead %s successfully.\n"
	{}

9 "Failed to %s.\n"
	{}

10 "The name "%s" is for internal use only.\nPlease use other name.\n"
	{}

11 "Cannot find the %s %s.\n"
	{}

12 "Value "%s" is not a valid value for "%s" option, please correct it.\n"
	{}

13 "Setting view %s status successfully.\n"
	{}

14 "%s"
	{}

15 "%s (%s).\n"
	{}

16 "Command line option syntax error, please refer to help.\n"
	{}
